app:
  mode: advanced

appearance:
  tint_color: "#0D6EFD"
  background_color:
    light: "#FFFFFF"
    dark: "#212529"
  status_bar_color:
    light: "#F8F9FA"
    dark: "#2B3035"

tabs:
  - title: Links
    path: /links
    icon: link
  - title: Tags
    path: /tags
    icon: tag
  - title: Search
    path: /search
    icon: magnifyingglass
    search: true
