app:
  mode: advanced

auth:
  oauth_paths:
    - /auth/apple

appearance:
  tint_color: "#166534"
  background_color:
    light: "#FAFAFA"
    dark: "#171717"

tabs:
  - title: Explore
    path: /explore
    icon: binoculars
  - title: Passport
    path: /passport
    icon: wallet.bifold
  - title: Profile
    path: /profile
    icon: person

screenshots:
  paths:
    - /explore
    - /passport
    - /profile

ruby_native:
  app_id: app_d4zsssgz
