app:
  mode: advanced

auth:
  oauth_paths:
    - /auth/apple

appearance:
  tint_color: "#166534"
  background_color:
    light: "#FAFAFA"
    dark: "#171717"

tabs:
  - title: Explore
    path: /explore
    icons:
      ios: binoculars
      android: travel_explore
    auto_route:
      - /explore
      - /breweries/
      - /neighborhoods/
  - title: Passport
    path: /passport
    icons:
      ios: wallet.bifold
      android: account_balance_wallet
  - title: Profile
    path: /profile
    icons:
      ios: person
      android: person

screenshots:
  paths:
    - /explore
    - /passport
    - /profile

ruby_native:
  app_id: app_d4zsssgz
