appearance:
  tint_color: "#4F46E5"
  background_color:
    light: "#F9FAFB"
    dark: "#1C1C1E"

tabs:
  - title: Today
    path: /today
    icon: calendar
  - title: Habits
    path: /habits
    icon: list.bullet
  - title: Profile
    path: /profile
    icon: person

screenshots:
  paths:
    - /today
    - /habits
    - /profile

ruby_native:
  app_id: app_d4zsssgz
