source "https://rubygems.org"

gem "rails", "~> 8.1.2"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "cgi", ">= 0.4.2"
gem "propshaft"
gem "puma", ">= 5.0"
gem "sqlite3", ">= 2.1"
gem "tzinfo-data", platforms: %i[windows jruby]

# Hotwire frontend.
gem "importmap-rails"
gem "stimulus-rails"
gem "turbo-rails"

# Native bridge.
gem_path = File.expand_path("../../gem", __dir__)
if File.exist?(gem_path)
  gem "ruby_native", path: gem_path
else
  gem "ruby_native"
end

# Push notifications.
gem "action_push_native"

# In-app purchases.
purchasekit_path = File.expand_path("../../../purchasekit/gem", __dir__)
if File.exist?(purchasekit_path)
  gem "purchasekit", path: purchasekit_path
else
  gem "purchasekit"
end

group :development do
  gem "web-console"
end
