source "https://rubygems.org"

gem "rails", "~> 8.1.2"

gem "bcrypt", "~> 3.1.7"
gem "bootsnap", require: false
gem "cgi", ">= 0.4.2"
gem "propshaft"
gem "puma", ">= 5.0"
gem "sqlite3", ">= 2.1"
gem "tzinfo-data", platforms: %i[windows jruby]

# Hotwire frontend.
gem "importmap-rails"
gem "stimulus-rails"
gem "turbo-rails"

# Native bridge.
gemfile_local = File.join(__dir__, "Gemfile.local")
if File.exist?(gemfile_local)
  eval_gemfile(gemfile_local)
else
  gem "ruby_native"
end

# Push notifications.
gem "action_push_native"

group :development do
  gem "web-console"
end
